# Generated by Django 4.2 on 2024-01-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shirts',
            new_name='Shirt',
        ),
    ]
