# Generated by Django 4.2 on 2024-02-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
