# Generated by Django 4.2 on 2024-02-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
