# Generated by Django 4.2 on 2024-02-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_delete_categories_delete_shirt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
